spring:
  application:
    name: Authentication
  data:
    mongodb:
      uri: mongodb://localhost:27017
      database: authentication_db

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs
  openapi:
    enabled: true

server:
  port: 8080
  servlet:
    context-path: /api/v1
